apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    type: postgres-db
    author: vamsi
spec:
  containers:
    - name: mypostgresdb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: mydb123456
          name: POSTGRES_USER
          value: myuser
          name: POSTGRES_DB
          value: mydb
      ports:
        - containerPort: 5432
...

