---
apiVersion: v1
kind: Service
metadata:
  name: redis-pod-service
  labels:
    type: redis-service
    author: vamsi
spec:
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    type: redis-db
    author: vamsi
...