---
apiVersion: v1
kind: Service
metadata:
  name: resulting-app-service
  labels:
    type: result-service
    author: vamsi
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: result-app
    author: vamsi
...