---
apiVersion: v1
kind: Pod
metadata:
  name: resuly-app-pod
  labels:
    type: result-app
    author: vamsi
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
       - containerPort: 80
...