---
apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    type: voting-app
    author: vamsi
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
       - containerPort: 80
...