---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    type: voting-service
    author: vamsi
spec:
  type: LodeBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: voting-app
    author: vamsi
...