---
apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    type: worker-app
    author: vamsi
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
...
